repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace    # удаляет пробелы в конце строк
      - id: end-of-file-fixer      # добавляет пустую строку в конце файла
        exclude: ^requirements\.txt$
      - id: check-yaml            # проверяет синтаксис YAML файлов
      - id: check-added-large-files # проверяет большие файлы

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=88]  # форматирует Python код

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]  # сортирует импорты

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203]  # проверяет стиль кода
